parameters:
- name: environmentName
  type: string
- name: serviceConnection
  type: string

jobs:
- deployment: deploy_adf
  displayName: 'Deploy to Azure Data Factory'
  pool:
    vmImage: 'windows-2019'
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: dataops_adfpublish
          path: 'adf_publish' 

        - task: AzurePowerShell@4
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            ScriptPath: '$(Build.SourcesDirectory)\adf\_scripts\deploymentadf.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $true'
            azurePowerShellVersion: LatestVersion
          displayName: 'Azure PowerShell script: Stop ADF triggers'

        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on $(rgName)'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: '$(rgName)'
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)\adf_publish\ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)\adf_publish\ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName "$(adfName)" -P_Ingest_MelbParkingData_properties_0_typeProperties_notebookPath "$(databricksNotebookPath)/02_standardize" -P_Ingest_MelbParkingData_properties_0_typeProperties_0_egg "$(databricksDbfsLibPath)/$(packageWheelName)" -P_Ingest_MelbParkingData_properties_4_typeProperties_0_egg "$(databricksDbfsLibPath)/$(packageWheelName)" -Ls_AdlsGen2_01_properties_typeProperties_url "https://$(datalakeAccountName).dfs.core.windows.net/" -Ls_KeyVault_01_properties_typeProperties_baseUrl "$(kvUrl)" -Ls_Rest_MelParkSensors_01_properties_typeProperties_url "$(apiBaseUrl)" -P_Ingest_MelbParkingData_properties_4_typeProperties_notebookPath "$(databricksNotebookPath)/03_transform" -Ls_AzureDatabricks_01_properties_typeProperties_domain "$(databricksDomain)" -Ls_AzureDatabricks_01_properties_typeProperties_workspaceResourceId "$(databricksWorkspaceResourceId)"

        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Start ADF triggers'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            ScriptPath: '$(Build.SourcesDirectory)\adf\_scripts\deploymentadf.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $false'
            azurePowerShellVersion: LatestVersion